program: src/mlops_day2/train_sweep.py
name: sweep test
method: bayes
metric:
  goal: minimize
  name: loss
parameters:
  lr:
    min: 0.0001
    max: 0.1
  batch-size:
    values: [16, 32, 64]
  epochs:
    values: [5, 10, 15]